// "MALAAR",
//"BADAJE",
// "MADANGHAL",
//"POYYA",
// "CHOUKI",
//     "Chowki",
// "BATIYADUKKA",

export const unitList = {
  BAKRABAIL: [
    "BADIMALE",
    "BAKRABAIL",
    "BOLMAR NORTH",
    "BOLMAR SOUTH",
    "CM NAGAR",
    "KAJE",
    "KOOTTURASTHE",
    "KUDUMBALACHIL",
    "NADIBAIL",
    "THALAKKI",
  ],
  DAIGOLI: [
    "ADAKALAKATTE",
    "ANEKKALLU",
    "DAIGOLI",
    "GUVEDAPADUPPU",
    "KUNTAPADAVU",
    "PALLEDAPADPU",
    "POYYATHBAIL",
    "POYYATHBAIL NORTH",
    "SULLIYAME",
    "URNI",
  ],
  KADAMBAR: [
    "ARIMALA",
    "CM NAGAR M",
    "DARKAS",
    "DURGIPALLA",
    "EDIYA",
    "KADAMBAR",
    "KADAMBAR SCHOOL",
    "KAJOOR",
    "MACHAMPADI",
    "PAPILA",
    "PUCHATHABAIL",
  ],

  KEDUMBADY: [
    "AMAI",
    "BACHALIKE",
    "BAKIMAR",
    "GERUKATE",
    "KEDUMBADI",
    "KEDUMBADI BAIL",
    "KOPPALA",
    "MUDIMAR",
    "PAVOOR",
    "SUNNAMGALA",
    "THOKE BADRIYA",
  ],

  KUNJATHUR: [
    "BS NAGAR",
    "HARWAR",
    "HYGLODHI",
    "IRSHAD NAGAR",
    "KUCHIKAD",
    "KUNJATHUR",
    "MOULANA ROAD",
    "SANNADKA",
    "TENTH MILE",
    "THUMINAD",
    "UDYAWARAM",
  ],

  MANJESHWARAM: [
    "AKKARA",
    "BEJJA",
    "CHECKPOST",
    "GUDDAGERI",
    "HOSANGADI",
    "MAJIBAIL",
    "MANJESHWARAM",
    "MOODAMBAIL",
    "PADATHUR",
    "PANDYAL",
    "POSOAT",
    "RAILWAY",
    "VALIYAVALAPP",
    "VAMANJOOR",
  ],

  MEENJA: [
    "BADAVI NAGAR",
    "BALIYUR",
    "BATTIPPADAVU",
    "BEJJANGALA",
    "BERIKE",
    "BORKALA",
    "CHIGURUPADHE",
    "JISTHIYA",
    "KULAVAIL",
    "MIYAPPADAVU",
    "MUNNIPPADY",
    "SANTHADKA",
    "THALAKALA",
  ],
  VORKADY: [
    "BAKERY JUNCTION",
    "DHARMA NAGAR",
    "GANDHI NAGAR",
    "KOLIYOOR",
    "KOLIYOOR PADAVU",
    "KOTEMAR",
    "MAJIRPALLA",
    "MORTHANA",
    "NACHAPADAVU",
    "ORUPANGODI",
    "PURUSHANKODI",
    "THOKE",
  ],
};

export const sectorList = [
  "BAKRABAIL",
  "DAIGOLI",
  "KADAMBAR",
  "KEDUMBADY",
  "KUNJATHUR",
  "MANJESHWARAM",
  "MEENJA",
  "VORKADY",
];

export const divisionList = ["MANJESHWARAM"];
